### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by xanxuso** [megvii-research/DCLS-SR#10]
您好，关于您论文中3.3节，有几个问题：
1、公式（10）是怎么得到的，需要最小化的不应该是||GiX↓s—Ri||2吗,就像Deep Wiener Decovolution中的公式（4a）。
2、为什么在特征空间中，平滑滤波器P和拉格朗日乘子可能不一致？如何理解？
3、为什么利用神经网络也就是代码中的self.grad_filter可以预测出来一组具有隐式拉格朗日乘数的平滑滤波器，怎么体现的呢？什么原理？

**Comment by Algolzw** [comment]
1、公式（10）的目的是期望去模糊后的特征尽可能少artifacts和noises同时满足公式（9）条件。注意公式（10）里的objective function $C$是基于梯度的，跟winner deconvolution的直接求解不一样。

2、如果把一个正常训练的SR网络的中间特征打印出来，可以发现各个通道的特征稀疏度以及平滑度都是不一样的（想象图像被分解为了多个基向量，有的主要代表平滑部分，有的代表边缘、纹理等）。如果梯度相差很大那么只用一个拉普拉斯算子以及拉格朗日乘数显然是不好处理的，因此我们选择用网络来学习。

3、原本我们想学的是一个拉格朗日乘数lambda和对应的平滑算子P，这里是为了简单相当于我们直接学了一个类似于sqrt(1/lambda)*P的结果（参考公式14）。

**Comment by xanxuso** [comment]
非常感谢您的回答，我再理解了一下：
1、第一点也就是说利用梯度算子计算去模糊特征每个通道中存在的artifacts和noises，然后构造拉格朗日方程以最小化这些error。
2、我原本以为这里的不一致指的是单个通道下平滑算子和拉格朗日乘子不一致，所以陷入了困惑。经过您的点拨，理解了每个通道对应一组平滑算子和拉格朗日乘子，然后各组之间是不一致的

**Comment by Algolzw** [comment]
@xanxuso 是的哈，祝好。
