### ISSUE TITLE
setting2的训练

### ISSUE THREAD

**Issue by tonia86** [megvii-research/DCLS-SR#14]
![1365F9EC756166DC7F094795CB1B6FCE](https://user-images.githubusercontent.com/100500382/183246655-bc69a7cf-d7d3-4fdb-b019-e214b1a779bd.jpeg)

再次感谢您精彩的工作！当我在复现您的代码时，在训练过程中，验证集的PSNR值突然的下降，问题是出在哪里的呢？希望您能指点一下。

**Comment by Algolzw** [comment]
这应该是训练崩掉了，建议是停掉程序并加载上一个完好的训练节点继续训练（如你这里的log可以从26000或24000节点继续训练具体可以参考[这个issue](https://github.com/megvii-research/DCLS-SR/issues/2)）。目前我正在排查程序容易崩的原因，修改重建部分的网络初始化方式或许可以在一定程度稍微缓解这个问题。

**Comment by tonia86** [comment]
好的，感谢您的解答。
