### ISSUE TITLE
关于论文中Figure11的问题

### ISSUE THREAD

**Issue by TTZ56952** [megvii-research/DCLS-SR#17]
您好，请问这个模型可以泛化到真实世界的图像上吗？
我使用了论文中的权重，测试在真实图像上的效果，发现效果并不是很好，是因为Setting1和Setting2的权重只是使用了模糊，没有加噪声进去训练的缘故吗？
并且想请问您在论文中Figure11的真实图片的结果中，使用的是哪个权重？谢谢！

**Comment by Algolzw** [comment]
使用的是setting1模型，但目前就我们的实验来看，合成数据上训练的blindSR模型泛化效果都不太好。未加噪声是一种原因，个人认为另一个原因是合成的模糊核不够全面覆盖不了真实场景，更好的数据合成方式可以参考Real-ESRGAN的paper。

**Comment by TTZ56952** [comment]
非常感谢您的解答！
