### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by haha0909** [megvii-research/DCLS-SR#19]
作者你好，我在用你的训练权重测试时，出现了如下报错：
![image](https://user-images.githubusercontent.com/92433693/196633676-5d63cf72-b589-48af-bdef-7022759b78ce.png)
我的测试步骤如下：1. 将测试的HR、LR分别用create_lmbd.py生成lmbd文件；
2. 修改test_setting1_x4.yml文件中的路径；
![image](https://user-images.githubusercontent.com/92433693/196635060-4733e863-13ef-4d01-9ec3-a73ee8a6f0a8.png)
3. 运行测试文件。
不知道是哪一步出了问题，望指正

**Comment by Algolzw** [comment]
看配置文件好像没问题，你能否把输入网络的LR图像保存下来看一下是否正常呢

**Comment by haha0909** [comment]
> 看配置文件好像没问题，你能否把输入网络的LR图像保存下来看一下是否正常呢

已经解决了，感谢回复！
