### ISSUE TITLE
How can we use this model to train on real low resolution images without super-resolution images?

### ISSUE THREAD

**Issue by Jiaxin-lucky** [megvii-research/DCLS-SR#21]
I am a new researcher in super-resolution work, for Blind Image Super-Resolution, I think we cannot get the SR image information and true kernel. But in your work, you have used this information, maybe this is not Blind Image Super-Resolution?

**Comment by Algolzw** [comment]
Although the ground truth kernels are required in training, we don't need them in testing. In other words, once the model is well-trained, we can directly apply it to any image, estimating the kernel and recovering a high-resolution version. So the inference is exactly the 'blind' super-resolution.

**Comment by javey-q** [comment]
> Although the ground truth kernels are required in training, we don't need them in testing. In other words, once the model is well-trained, we can directly apply it to any image, estimating the kernel and recovering a high-resolution version. So the inference is exactly the 'blind' super-resolution.

作者您好，感谢您做出的优秀工作，关于以上讨论我还有些问题想请教一下：我看您的论文和代码中，在每次训练过程中，关于模糊核的类型和尺寸都是特定的，这样如果在不确定测试集的模糊核类型和大小的情况下，是否效果就不行了？  
进一步地，为了解决上述问题，如果在训练过程中让模糊核的类型和尺寸都是随机的，这样您的方法还是否适用呢？
刚接触这个领域不久，有理解不对的还请谅解。

**Comment by Algolzw** [comment]
理论上确实如此，测试集模糊核不确定的话效果肯定会变差。不过我没有试过随机类型或尺寸模糊核，这个也许可以参考下Real-ESRGAN。
