### ISSUE TITLE
训练数据准备的问题

### ISSUE THREAD

**Issue by EchoXu98** [megvii-research/DCLS-SR#22]
您好，在您的README中“Dataset Preparation”节写到“To transform datasets to binary files for efficient IO, run:”，但是当我运行create_lmdb.py文件时，并不知道其中的img_folder应该指向什么样的训练数据路径。换句话说，在生成训练数据时，我应该将img_folder设置为DIV2K的HR图像，还是DIV2Kx4下的LR图像？

**Comment by Algolzw** [comment]
你需要分开转，处理HR图像时img_folder指向HR目录，处理LR图像时img_folder指向LR目录。

**Comment by EchoXu98** [comment]
谢谢你，感谢您百忙之中抽空回答！按照您的回答，我理解为在训练时是同时需要提供HR和LR数据吗？我是第一次接触Blind Image Super-Resolution问题，在复现的以往超分辨率工作中都只需要提供HR训练数据就好了。

**Comment by Algolzw** [comment]
训练只需要提供HR图像，验证和测试的才会同时用到LR和HR。准备训练集的话你只需要提供HR数据集就好了

**Comment by EchoXu98** [comment]
好的，谢谢您！

**Comment by YoungP2001** [comment]
我也想问一下，按setting1训练时验证集是set5，这里的set5是直接下载的那40张，还是经过generate_mod_blur_LR_bic.py处理后再做验证集？

**Comment by Algolzw** [comment]
40张set5如果是Gaussian8处理后的那可以直接用，如果只有5张HR图像，则需要使用脚本生成40张LR后再做验证集。

**Comment by YoungP2001** [comment]
> 40张set5如果是Gaussian8处理后的那可以直接用，如果只有5张HR图像，则需要使用脚本生成40张LR后再做验证集。

所以验证集还是得经过Gaussian8处理，不能直接用set5官网下载的40张LR图像。

**Comment by Algolzw** [comment]
是的

**Comment by YoungP2001** [comment]
> 是的

谢谢
