### ISSUE TITLE
About comparisons in figure 7 and table 4.

### ISSUE THREAD

**Issue by fuuuyuuu** [megvii-research/DCLS-SR#23]
您好，非常感谢您的工作！

在文中您提到，对于模糊核估计阶段，使用转换后的模糊核作为监督，因此估计出的也应该是转换后的模糊核。但在图7和表4中，似乎您展示的是在原始模糊核域上的对比，想请问是如何将估计出的模糊核变换回原始模糊核域的？

**Comment by Algolzw** [comment]
Figure 7 和 Table 4的实验室是表明Dynamic Deep Linear Kernel (DDLK) 的作用，这个实验并没有采用转换后的模糊核，而是学习原始kernel以便与其他模型公平比较。

**Comment by fuuuyuuu** [comment]
> 

感谢您的回复！
所以说，是单独对DDLK模块训练了一次，针对lr -> 原始kernel的模糊核估计任务？
如果是这样的话大概明白了，就是稍微跟前面intro部分说的"It transfers the kernel estimation into the LR space and the new kernel can be estimated without aliasing ambiguity."有点出入了，非常感谢您。
