### ISSUE TITLE
预训练权重

### ISSUE THREAD

**Issue by cc12345666** [megvii-research/DCLS-SR#26]
您好，提供的预训练权重链接我这边无法下载，请问是否有百度网盘或者百度云其他的下载方式？

**Comment by Algolzw** [comment]
Sure, I provide it here: 
https://pan.baidu.com/s/1hy-RZ4qeC44hFnGRCj2JlQ?pwd=3ife 提取码: 3ife

**Comment by cc12345666** [comment]
谢谢
