### ISSUE TITLE
用提供的模型来测试set5,PSNR很低

### ISSUE THREAD

**Issue by YoungP2001** [megvii-research/DCLS-SR#28]
您好,请问我用您给的模型来测试set5,PSNR只有7左右,生成的result文件里面图片是全黑的,是什么问题呢?

**Comment by YoungP2001** [comment]
是fft的问题,ifft不需要取实部

**Comment by Algolzw** [comment]
你是用的高版本pytorch吗？高版本确实需要修改一下fft部分。

**Comment by YoungP2001** [comment]
![图片](https://user-images.githubusercontent.com/62990543/220882858-21abea8c-8280-4401-b290-b1ef4fc5da2b.png)
是用的高版本,然后改成了这个但不行,后来按照其他问题里您给的回答改了就可以了,不知道为什么

**Comment by Algolzw** [comment]
pytorch不同版本对fft的实现很不一样，我也是试出来的。改了没问题那就好。

**Comment by YoungP2001** [comment]
感谢
