### ISSUE TITLE
如何从上一次训练断开处重新训练？

### ISSUE THREAD

**Issue by YoungP2001** [megvii-research/DCLS-SR#30]
您好，小白刚接触深度学习这方面，之前训练老是断开，还没有完成过一次。想问您怎么从上一次断开处重新训练？
我看见option的path里有  
pretrain_model_G: ~
strict_load: true
resume_state: ~  # true
还有断开时的迭代次数和epoch怎么得到，我该怎么改代码？

**Comment by Algolzw** [comment]
你好，可以在log里你的project下面的training_state目录下面找到最近的节点，然后option中设置
`resume_state: log/project_name/training_state/xxxx.state`
即可以断点重训。

**Comment by YoungP2001** [comment]
> 你好，可以在log里你的project下面的training_state目录下面找到最近的节点，然后option中设置 `resume_state: log/project_name/training_state/xxxx.state` 即可以断点重训。

那这个呢
![001C10A1](https://user-images.githubusercontent.com/62990543/222870215-6a62ffc1-f454-4640-99df-c8af0f93c841.png)
pretrain_model_G: 是要上一次的模型路径？
strict_load: 这个是什么意思？

**Comment by Algolzw** [comment]
单纯断点重训的话pretrain_model_G这个不用管，它会从training_state里面自动加载对应的模型。strict_load是指要求加载的模型参数要和当前代码中的模型参数保持一致，一般设置为true就好。

**Comment by YoungP2001** [comment]
> 单纯断点重训的话pretrain_model_G这个不用管，它会从training_state里面自动加载对应的模型。strict_load是指要求加载的模型参数要和当前代码中的模型参数保持一致，一般设置为true就好。

明白了，感谢！
