### ISSUE TITLE
算法相关问题

### ISSUE THREAD

**Issue by cc12345666** [megvii-research/DCLS-SR#31]
作者您好，感谢您的工作。
我在您的论文中理解到，模糊核是在算法中只在LR空间进行估计，并不像DAN算法那样将重建图像也加入到核估计算法中采用递归的进行迭代优化，我想了解一下这个理解是否正确，并想问在DCLS算法训练中对于图像的模糊核是只进行了一次估计吗？期待您的回复。

**Comment by Algolzw** [comment]
是的，我们并没有采用递归的方式去学习。在LR空间下相对比较容易估计模糊核，因此一次估计并基于此恢复图像即可。

**Comment by cc12345666** [comment]
好的，非常感谢
