### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by Aazsy** [megvii-research/DCLS-SR#36]
刚接触深度学习，请问预训练模型是哪个呀，是DCLSx4_setting1.pth这个文件吗？文件里面也找不到DCLSx4_setting1.pth这个文件。

**Comment by Algolzw** [comment]
所有的预训练我都放在[这里](https://drive.google.com/drive/folders/135xCCLWSylBaNxh6B3I_UnCeox8AkVzC?usp=sharing)了

**Comment by Aazsy** [comment]
好的，谢谢啦。
