### ISSUE TITLE
关于模糊和采样的顺序问题

### ISSUE THREAD

**Issue by sixgod696** [megvii-research/DCLS-SR#37]
想请教下，既然调转了采样和模糊的顺序，那么先去模糊再上采样，走样问题该如何解决?上采样的插值过程不会造成图片走样吗？

**Comment by Algolzw** [comment]
你好，降质的时候按我们论文里的方法调转顺序是不会有走样的哈，而上采样过程其实和其它超分论文一样，因为照着GT学所以一般不会有走样。而且我们也同时输入了去模糊前的特征减小去卷积带来的artifacts。

**Comment by sixgod696** [comment]
> 

好的，谢谢解惑
