### ISSUE TITLE
关于feature的问题

### ISSUE THREAD

**Issue by Synapsess** [megvii-research/DCLS-SR#41]
您好，根据论文,DCLS是在特征空间上进行的，特征是在原始的lr上线性变换得到的。但是网络结构中使用了resblock得到了特征，显然resblock是有激活函数，因而是非线性的，请问这应该怎么理解呢？
<img width="456" alt="1687850936451" src="https://github.com/megvii-research/DCLS-SR/assets/100500406/9257a976-a228-438c-a66d-d04fad82bd82">
<img width="626" alt="1687851135855" src="https://github.com/megvii-research/DCLS-SR/assets/100500406/6e9a0caa-2a11-470f-b2b9-fa9900c9b99d">

**Comment by Algolzw** [comment]
Hi, a deep neural network (DNN) can be locally linear, but of course it will produce more artifacts than linear network. This problem is mentioned in the DCLS section. To address it , we use the dual path network that inputs both original features and deblurred features.

**Comment by Synapsess** [comment]
感谢回复，感觉您对自己的paper和project都很上心

**Comment by Algolzw** [comment]
感谢认可😁

**Comment by Synapsess** [comment]
据我简单的实验，训练过程中的crash多半是CAlayer引起的。在DANv2中应该是因为两通道之间的乘法操作，而不是通常的cat。一点看法，不一定对。

According my simple experiment,crash is likely caused by CAlayer which is different from DANv2.Unstablilty in DANv2 is caused by multiple operation.
