### ISSUE TITLE
为什么训练时的模糊核，X2 、X3、X4的方差设置为[0.2,2] [0.2,3]  [0.2,4]

### ISSUE THREAD

**Issue by lanhoulllllllllll** [megvii-research/DCLS-SR#48]
您好您好，我有一个问题，为啥训练时随机模糊核的范围的这么设置啊，还有测试时使用的高斯8模糊核方差对于不同的超分倍数也有不同的范围，我看ikc里也是这么设置的
![image](https://github.com/megvii-research/DCLS-SR/assets/121162076/6ddca789-5ce3-4c6f-b094-27e451d95524)
![image](https://github.com/megvii-research/DCLS-SR/assets/121162076/01adaf3a-c434-4e2d-b8a1-ebc311198d50)

**Comment by Algolzw** [comment]
你好，这个我就是跟着IKC设置的= =（为了保证公平的比较结果）。 通常来说图像缩小倍率越大越模糊，所以使用较大范围的kernel训练高倍率模型。Gaussian8则是取了训练kernel width范围的偏中间的值，这样超分效果会好一些。当然你也可以使用别的设置，但那样的话通常就需要对其他模型重新训练和测试了。

**Comment by lanhoulllllllllll** [comment]
好的，明白了
